name: ollapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI and Design
  cupertino_icons: ^1.0.6
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.10+1

  # State Management
  provider: ^6.0.5

  # Calendar and Date
  table_calendar: ^3.1.2
  intl: ^0.19.0

  # Networking
  http: ^1.2.2
  url_launcher: ^6.0.12

  # Firebase
  cloud_firestore: ^5.6.0
  firebase_messaging: ^15.1.6
  path_provider: ^2.0.15
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  firebase_storage: ^12.2.0
  firebase_database: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/