// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTNCPmZhUjzQaJnknwqAn2b9dcj1C5sY0',
    appId: '1:233197671362:web:857c6dfc190ed28baefc5b',
    messagingSenderId: '233197671362',
    projectId: 'hallowed-fin-349908',
    authDomain: 'hallowed-fin-349908.firebaseapp.com',
    storageBucket: 'hallowed-fin-349908.appspot.com',
    measurementId: 'G-F0KPLM6B4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJYAAWNJVwlTF24C3u6ZmMPD3HsV-rB3k',
    appId: '1:233197671362:android:2c16a42dc2005a4aaefc5b',
    messagingSenderId: '233197671362',
    projectId: 'hallowed-fin-349908',
    storageBucket: 'hallowed-fin-349908.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlDAehPpzCad4JW5zYJ6VdSAus-A433zY',
    appId: '1:233197671362:ios:e4c71019e9cf591caefc5b',
    messagingSenderId: '233197671362',
    projectId: 'hallowed-fin-349908',
    storageBucket: 'hallowed-fin-349908.appspot.com',
    iosClientId: '233197671362-so0qq5og6km8h58p674su1esmq5gkjkv.apps.googleusercontent.com',
    iosBundleId: 'com.example.ollapp',
  );
}
