// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-f1afwFMg-0aafrtI1-w6CaoFkwC2fTw',
    appId: '1:535015116281:web:61d748a94e94f653e88128',
    messagingSenderId: '535015116281',
    projectId: 'zresume-67ec9',
    authDomain: 'zresume-67ec9.firebaseapp.com',
    storageBucket: 'zresume-67ec9.appspot.com',
    measurementId: 'G-S8C968JW36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-tGZOK6SVm9EWEqqbova6KvMwPCvPmh8',
    appId: '1:535015116281:android:52520383ded0e1a4e88128',
    messagingSenderId: '535015116281',
    projectId: 'zresume-67ec9',
    storageBucket: 'zresume-67ec9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyBBu5HDN6cGPP5ZmF8ufej6nU4nn4NAE',
    appId: '1:535015116281:ios:c41ab1c60e994422e88128',
    messagingSenderId: '535015116281',
    projectId: 'zresume-67ec9',
    storageBucket: 'zresume-67ec9.appspot.com',
    androidClientId: '535015116281-f8qkrpp4ngeemn4mps3rjnvjmct8had4.apps.googleusercontent.com',
    iosClientId: '535015116281-o413i6g6bjjvdp39g1o8jfaaj04u4n95.apps.googleusercontent.com',
    iosBundleId: 'com.example.ollapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyBBu5HDN6cGPP5ZmF8ufej6nU4nn4NAE',
    appId: '1:535015116281:ios:9349334b70b4ba28e88128',
    messagingSenderId: '535015116281',
    projectId: 'zresume-67ec9',
    storageBucket: 'zresume-67ec9.appspot.com',
    androidClientId: '535015116281-f8qkrpp4ngeemn4mps3rjnvjmct8had4.apps.googleusercontent.com',
    iosClientId: '535015116281-6uudfubg8aoo5qov6sa6r5h975a7tg9t.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-f1afwFMg-0aafrtI1-w6CaoFkwC2fTw',
    appId: '1:535015116281:web:55ae7cea643d5c75e88128',
    messagingSenderId: '535015116281',
    projectId: 'zresume-67ec9',
    authDomain: 'zresume-67ec9.firebaseapp.com',
    storageBucket: 'zresume-67ec9.appspot.com',
    measurementId: 'G-7WRVCK9YCY',
  );

}